os:
  - osx
  - linux
osx_image: xcode9
language: generic
branches:
  only:
    - develop
    - master
xcode_workspace: DockTracker.xcworkspace # path to your xcodeproj folder
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X